spring:
  messages:
    basename: i18n.login  # 国际化配置
  datasource:             # 数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_management?serverTimezone=GMT%2b8&useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 52780
  thymeleaf:
    cache: false  # 关闭thymeleaf的缓存
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss # 修改默认日期格式
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
#      location: /public  #指定的临时目录来存储上传的文件

mybatis-plus:   # mybatis-plus配置
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志输出
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl #关闭日志输出
  mapper-locations: classpath:mybatis/*.xml  # xml文件的位置配置
  type-aliases-package: sm.pojo        # 别名